# Generated by Django 3.1.5 on 2021-01-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(db_index=True, max_length=150, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Теги',
                'verbose_name_plural': 'Теги',
                'ordering': ['tags'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Навание товара')),
                ('description', models.TextField(blank=True)),
                ('seller', models.CharField(max_length=100, verbose_name='Имя продавца')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.tags')),
            ],
        ),
    ]
