# Generated by Django 3.1.5 on 2021-01-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_price'),
        ('shop', '0002_auto_20210126_0706'),
    ]

    operations = [
    ]
