# Generated by Django 3.1.5 on 2021-01-26 15:23

from django.db import migrations, models
from random import randint

def set_random_price(apps, schema_editor):

    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        product.price = randint(10,100)
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_merge_20210126_1518'),
    ]

    operations = [
        migrations.RunPython(set_random_price),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
