# Generated by Django 3.1.5 on 2021-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210202_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='shop.Tags'),
        ),
    ]
